半定値対称行列の近似

https://www.sciencedirect.com/science/article/pii/0024379588902236

数値計算的に上手く行かないことがある

In [1]:
import numpy as np
from scipy.linalg import polar

def get_nearest_psd(A: np.ndarray) -> np.ndarray:
    
    B = .5 * (A.T + A)
    _, H = polar(B)
    return (B + H) / 2


def get_near_psd(A):
    C = (A + A.T)/2
    eigval, eigvec = np.linalg.eig(C)
    # eigval[eigval < 0] = 0
    eigval[eigval <= 0] = eigval.mean() * 1e-6

    return eigvec.dot(np.diag(eigval)).dot(eigvec.T)

In [2]:
"""
不定値な対称行列の生成
"""

shape = 10, 10

# ランダムな正方行列の生成
A = np.random.rand(shape[0], shape[1])

# ランダムで対角成分を0にする
mask = np.random.choice([True, False], size=A.shape, p=[0.5, 0.5])
A *= mask

# 対称行列にする
A = 0.5 * (A + A.T)

display(A)

# 固有値の計算
eigenvalues = np.linalg.eigvals(A)
print(eigenvalues)
print()

# 定値性のチェック
res = eigenvalues.min() >= 0 or eigenvalues.max() <= 0
print(f'Is this definite?: {res}')

array([[0.02254727, 0.45566756, 0.04767052, 0.05121898, 0.49980294,
        0.        , 0.08576551, 0.49308075, 0.        , 0.32646319],
       [0.45566756, 0.44197871, 0.26819455, 0.11958827, 0.44970108,
        0.        , 0.        , 0.28706361, 0.71767919, 0.32366705],
       [0.04767052, 0.26819455, 0.        , 0.32314993, 0.49520799,
        0.22555837, 0.28376459, 0.        , 0.48892996, 0.26509313],
       [0.05121898, 0.11958827, 0.32314993, 0.        , 0.52157955,
        0.41661257, 0.46859083, 0.        , 0.23749702, 0.39289863],
       [0.49980294, 0.44970108, 0.49520799, 0.52157955, 0.74849213,
        0.        , 0.        , 0.36167288, 0.41634854, 0.15946084],
       [0.        , 0.        , 0.22555837, 0.41661257, 0.        ,
        0.        , 0.44288885, 0.        , 0.71429045, 0.        ],
       [0.08576551, 0.        , 0.28376459, 0.46859083, 0.        ,
        0.44288885, 0.        , 0.40235861, 0.        , 0.10579244],
       [0.49308075, 0.28706361, 0.       

[ 2.74680496  0.92786102 -1.06023685 -0.82249094  0.57170867  0.50011447
  0.11791047 -0.41794627 -0.25136608 -0.2798774 ]

Is this definite?: False


In [3]:
""" 
不定値対称行列を半正定値対称行列で近似

上手く行っていないが原因は不明
"""

B = get_nearest_psd(A)
display(B)

# 固有値の計算
eigenvalues = np.linalg.eigvals(B)
print(eigenvalues)
print()

# 定値性のチェック
res = eigenvalues.min() >= 0 or eigenvalues.max() <= 0
print(f'Is this definite?: {res}')

array([[ 0.31976747,  0.23614047, -0.03346853,  0.2259664 ,  0.01257394,
         0.16450718,  0.13398861,  0.12803958,  0.55047083,  0.18620041],
       [ 0.23614047,  0.59258324,  0.10181174,  0.05080365,  0.08509429,
         0.06018924,  0.18133221,  0.46108997,  0.48721009,  0.03216106],
       [-0.03346853,  0.10181174,  1.07159783,  0.08068603,  0.24339981,
         0.3722805 ,  0.41832862,  0.30768783,  0.08382433,  0.31232192],
       [ 0.2259664 ,  0.05080365,  0.08068603,  0.87491065,  0.2784234 ,
         0.02529412,  0.30287577, -0.05324453,  0.04944221,  0.21675224],
       [ 0.01257394,  0.08509429,  0.24339981,  0.2784234 ,  0.97793387,
         0.13281173,  0.06763179,  0.03624175,  0.00425346,  0.03122408],
       [ 0.16450718,  0.06018924,  0.3722805 ,  0.02529412,  0.13281173,
         0.32942312,  0.1743503 ,  0.0890508 ,  0.42231723,  0.25548329],
       [ 0.13398861,  0.18133221,  0.41832862,  0.30287577,  0.06763179,
         0.1743503 ,  0.30649254,  0.18437722

[ 2.44985532e+00  1.40097748e+00  1.04937725e+00  7.90924768e-01
  6.24592742e-01  2.46723963e-02  6.48544597e-16 -4.75254529e-16
 -1.16029668e-16 -1.70273613e-16]

Is this definite?: False


In [16]:
""" 
不定値対称行列を半正定値対称行列で近似
"""

C = get_near_psd(A)
display(C)

# 固有値の計算
eigenvalues = np.linalg.eigvals(C)
print(eigenvalues)
print()

# 定値性のチェック
res = eigenvalues.min() >= 0 or eigenvalues.max() <= 0
print(f'Is this definite?: {res}')

array([[ 0.31976777,  0.23614048, -0.0334685 ,  0.22596632,  0.01257395,
         0.1645072 ,  0.13398867,  0.12803953,  0.5504707 ,  0.18620035],
       [ 0.23614048,  0.59258338,  0.10181178,  0.05080366,  0.08509427,
         0.06018925,  0.18133208,  0.46108987,  0.48721004,  0.03216114],
       [-0.0334685 ,  0.10181178,  1.07159792,  0.08068605,  0.2433998 ,
         0.37228045,  0.41832857,  0.30768772,  0.08382438,  0.31232184],
       [ 0.22596632,  0.05080366,  0.08068605,  0.87491072,  0.27842338,
         0.02529419,  0.3028757 , -0.05324452,  0.04944225,  0.21675218],
       [ 0.01257395,  0.08509427,  0.2433998 ,  0.27842338,  0.97793388,
         0.13281169,  0.06763183,  0.03624176,  0.00425346,  0.03122411],
       [ 0.1645072 ,  0.06018925,  0.37228045,  0.02529419,  0.13281169,
         0.32942338,  0.17435021,  0.08905091,  0.42231713,  0.25548323],
       [ 0.13398867,  0.18133208,  0.41832857,  0.3028757 ,  0.06763183,
         0.17435021,  0.30649272,  0.18437729

[2.44985532e+00 1.40097748e+00 1.04937725e+00 7.90924768e-01
 6.24592742e-01 2.46723963e-02 4.21950140e-07 4.21950141e-07
 4.21950140e-07 4.21950141e-07]

Is this definite?: True


In [17]:
abs(A - C).max(), abs(A - B).max(), abs(B - C).max()

(0.3294233831149184, 0.3294231222991535, 3.2843139935456733e-07)

In [18]:
abs(A - C).mean(), abs(A - B).mean(), abs(B - C).mean()

(0.08826816022090983, 0.08826810331295437, 6.151452228352234e-08)

In [19]:
A.mean(), B.mean(), C.mean()

(0.2255175567801451, 0.22828972392219365, 0.22828972553188154)

In [4]:
np.linalg.eigvals(A)

array([ 2.74680496,  0.92786102, -1.06023685, -0.82249094,  0.57170867,
        0.50011447,  0.11791047, -0.41794627, -0.25136608, -0.2798774 ])

In [ ]:
# def _is_semi_definite(matrix: np.ndarray) -> bool:
def _is_negative_semi_definite(matrix: np.ndarray) -> bool:
    eig_vals = np.linalg.eigvals(matrix)
        
    # if np.all(eig_vals >= 0) or np.all(eig_vals <= 0):
    if np.all(eig_vals <= 0):
        return True
    else:
        return False

    
def get_near_nsd_matrix(A: np.ndarray) -> np.ndarray:
    if _is_negative_semi_definite(A):
        return A
    else:
        B = (A + A.T)/2
        eigval, eigvec = np.linalg.eig(B)
        # eigval[eigval < 0] = 0
        eigval[eigval >= 0] = - eigval.mean() * 1e-6
        return eigvec.dot(np.diag(eigval)).dot(eigvec.T)

In [6]:
def _is_positive_semi_definite(matrix: np.ndarray) -> bool:
    eig_vals = np.linalg.eigvals(matrix)
        
    if np.all(eig_vals >= 0):
        return True
    else:
        return False

def get_near_psd_matrix(A: np.ndarray) -> np.ndarray:
    if _is_positive_semi_definite(A):
        return A
    else:
        B = (A + A.T) / 2
        eigval, eigvec = np.linalg.eig(B)
        eigval[eigval <= 0] = eigval.mean() * 1e-6
        return eigvec.dot(np.diag(eigval)).dot(eigvec.T)

In [8]:
np.linalg.eigvals(A)

array([ 2.74680496,  0.92786102, -1.06023685, -0.82249094,  0.57170867,
        0.50011447,  0.11791047, -0.41794627, -0.25136608, -0.2798774 ])

In [10]:
H = get_near_psd_matrix(A)
np.linalg.eigvals(H)

array([2.74680496e+00+0.00000000e+00j, 9.27861024e-01+0.00000000e+00j,
       5.71708670e-01+0.00000000e+00j, 5.00114466e-01+0.00000000e+00j,
       1.17910472e-01+0.00000000e+00j, 2.03248206e-07+0.00000000e+00j,
       2.03248206e-07+0.00000000e+00j, 2.03248206e-07+5.19402403e-17j,
       2.03248206e-07-5.19402403e-17j, 2.03248206e-07+0.00000000e+00j])

In [11]:
np.linalg.eigvals(- H)

array([-2.74680496e+00+0.00000000e+00j, -9.27861024e-01+0.00000000e+00j,
       -5.71708670e-01+0.00000000e+00j, -5.00114466e-01+0.00000000e+00j,
       -1.17910472e-01+0.00000000e+00j, -2.03248206e-07+0.00000000e+00j,
       -2.03248206e-07+0.00000000e+00j, -2.03248206e-07+5.19402403e-17j,
       -2.03248206e-07-5.19402403e-17j, -2.03248206e-07+0.00000000e+00j])