In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys

project_dir_path = '/Users/keisukeonoue/ws/lukasiewicz_1'
sys.path.append(project_dir_path)

import cvxpy as cp
import numpy as np
import pandas as pd 

from src.setup_problem_dual_single_task import Setup

from src.objective_function_single_task import ObjectiveFunction
from src.predicate import Predicate_dual

In [3]:
data_dir_path = os.path.join(project_dir_path, 'inputs/pima_indian_diabetes_3/')
train_data_dir_path = os.path.join(data_dir_path, "train")
file_list = os.listdir(train_data_dir_path)

L_files = [filename for filename in file_list 
           if filename.startswith('L') and filename.endswith('.csv')]

U_files = [filename for filename in file_list 
           if filename.startswith('U') and filename.endswith('.csv')]

file_names_dict = {
    'supervised': L_files,
    'unsupervised': U_files,
    'rule': ['rules_3.txt']
}

train_data_dir_path = os.path.join(data_dir_path, "train")

In [4]:
train_data_file_path = os.path.join(data_dir_path, "test/L_Outcome.csv")
train_data_file_path

'/Users/keisukeonoue/ws/lukasiewicz_1/inputs/pima_indian_diabetes_3/test/L_Outcome.csv'

In [5]:
problem_instance = Setup(
    train_data_dir_path, 
    file_names_dict, 
    ObjectiveFunction, 
    'Outcome', 
    c1=100, 
    c2=10
)

objective, constraints = problem_instance.main()
problem = cp.Problem(objective, constraints)
result = problem.solve(verbose=True)

load_data took 0.05094599723815918 seconds!
load_rules took 0.035859107971191406 seconds!
formulate_predicates_with_cvxpy took 5.7220458984375e-05 seconds!
shape of P: (1807, 1807)
finish l
finish h
finish s
finish l h
finish l s
finish h s
_construct_P_j took 1.0823760032653809 seconds!
construct_constraints took 0.1726830005645752 seconds!
                                     CVXPY                                     
                                     v1.3.2                                    
(CVXPY) Feb 02 07:05:40 PM: Your problem has 36756 variables, 1257 constraints, and 0 parameters.


/Users/keisukeonoue/ws/lukasiewicz_2/myenv/lib/python3.11/site-packages/cvxpy/problems/problem.py:157: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
/Users/keisukeonoue/ws/lukasiewicz_2/myenv/lib/python3.11/site-packages/cvxpy/problems/problem.py:163: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "


(CVXPY) Feb 02 07:05:41 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Feb 02 07:05:41 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Feb 02 07:05:41 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Feb 02 07:05:41 PM: Compiling problem (target solver=OSQP).
(CVXPY) Feb 02 07:05:41 PM: Reduction chain: FlipObjective -> CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> OSQP
(CVXPY) Feb 02 07:05:41 PM: Applying reduction FlipObjective
(CVXPY) Feb 02 07:05:41 PM: Applying reduction CvxAttr2Constr
(CVXPY) Feb 02 07:05:41 PM: Applying reduction Qp2SymbolicQp


/Users/keisukeonoue/ws/lukasiewicz_2/myenv/lib/python3.11/site-packages/cvxpy/problems/problem.py:163: UserWarning: Constraint #4 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "


(CVXPY) Feb 02 07:05:41 PM: Applying reduction QpMatrixStuffing


/Users/keisukeonoue/ws/lukasiewicz_2/myenv/lib/python3.11/site-packages/cvxpy/problems/problem.py:163: UserWarning: Constraint #5 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "


(CVXPY) Feb 02 07:05:46 PM: Applying reduction OSQP
(CVXPY) Feb 02 07:05:46 PM: Finished problem compilation (took 4.981e+00 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Feb 02 07:05:46 PM: Invoking solver OSQP  to obtain a solution.
-----------------------------------------------------------------
           OSQP v0.6.3  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2021
-----------------------------------------------------------------
problem:  variables n = 38563, constraints m = 39820
          nnz(P) + nnz(A) = 1092163
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.0

In [6]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

p_trained = Predicate_dual(
    problem_instance, 
    'Outcome', 
    # metrics=accuracy_score,
    metrics=f1_score,
    opt_iter_num=100
)

[I 2024-02-02 19:06:08,942] A new study created in memory with name: no-name-49f44ad3-828d-4cb3-96b8-398ce8900a15
[I 2024-02-02 19:06:09,003] Trial 0 finished with value: 0.5242424242424243 and parameters: {'b': 0.3899658687614216}. Best is trial 0 with value: 0.5242424242424243.
[I 2024-02-02 19:06:09,011] Trial 1 finished with value: 0.0 and parameters: {'b': -2.492103068327247}. Best is trial 0 with value: 0.5242424242424243.
[I 2024-02-02 19:06:09,022] Trial 2 finished with value: 0.49014084507042255 and parameters: {'b': 0.7775385869791718}. Best is trial 0 with value: 0.5242424242424243.
[I 2024-02-02 19:06:09,042] Trial 3 finished with value: 0.0 and parameters: {'b': -1.5055379785647305}. Best is trial 0 with value: 0.5242424242424243.
[I 2024-02-02 19:06:09,075] Trial 4 finished with value: 0.49014084507042255 and parameters: {'b': 0.6156055890554746}. Best is trial 0 with value: 0.5242424242424243.
[I 2024-02-02 19:06:09,105] Trial 5 finished with value: 0.0 and parameters: {


min_bound: -3.0379200005446068
max_bound: 1.9620799994553935



[I 2024-02-02 19:06:09,160] Trial 8 finished with value: 0.5095168374816984 and parameters: {'b': 0.4023659850918522}. Best is trial 0 with value: 0.5242424242424243.
[I 2024-02-02 19:06:09,181] Trial 9 finished with value: 0.0 and parameters: {'b': -2.508738650222668}. Best is trial 0 with value: 0.5242424242424243.
[I 2024-02-02 19:06:09,208] Trial 10 finished with value: 0.49014084507042255 and parameters: {'b': 1.2736130194528705}. Best is trial 0 with value: 0.5242424242424243.
[I 2024-02-02 19:06:09,243] Trial 11 finished with value: 0.0 and parameters: {'b': 0.09436444282635409}. Best is trial 0 with value: 0.5242424242424243.
[I 2024-02-02 19:06:09,256] Trial 12 finished with value: 0.49014084507042255 and parameters: {'b': 1.846513113112695}. Best is trial 0 with value: 0.5242424242424243.
[I 2024-02-02 19:06:09,276] Trial 13 finished with value: 0.022727272727272724 and parameters: {'b': 0.14230334773316067}. Best is trial 0 with value: 0.5242424242424243.
[I 2024-02-02 19:06

In [7]:
p_trained.coeff

array([0.00996556, 0.08746423, 0.0659938 , 0.05620022, 0.06266074,
       0.06755724, 0.16267144, 0.32222718])

In [8]:
data = pd.read_csv(train_data_file_path, index_col=0)
X_test, y_test = data.drop(['target'], axis=1), data['target']

In [9]:
y_pred = p_trained(X_test)
y_pred

array([0.47521971, 0.66602939, 0.50186209, 0.4512903 , 0.48788827,
       0.55003206, 0.52622238, 0.45550454, 0.48089874, 0.47915841,
       0.43919612, 0.53441466, 0.55728412, 0.4492378 , 0.51214811,
       0.49630789, 0.57256275, 0.56980121, 0.47917749, 0.41404975,
       0.52691195, 0.43981908, 0.42908952, 0.52400906, 0.4528079 ,
       0.47849464, 0.50290956, 0.56752306, 0.42242419, 0.57350134,
       0.57528077, 0.49868805, 0.62369153, 0.56211841, 0.56478393,
       0.48006163, 0.43816659, 0.52810765, 0.60046216, 0.6090784 ,
       0.5755239 , 0.67137406, 0.58857193, 0.4571057 , 0.49892015,
       0.67105426, 0.55314154, 0.5512089 , 0.62720827, 0.590622  ,
       0.50118756, 0.52644279, 0.49324631, 0.60002467, 0.552272  ,
       0.52961735, 0.52024768, 0.49931521, 0.54272749, 0.55426511,
       0.47852833, 0.44440965, 0.51840604, 0.56378725, 0.56504294,
       0.63054261, 0.55301859, 0.4914675 , 0.58545212, 0.46389983,
       0.52185039, 0.51064942, 0.45777267, 0.5683777 , 0.60158

In [10]:
y_pred_interpreted = np.where(y_pred >= 0.5, 1, -1)
y_pred_interpreted

array([-1,  1,  1, -1, -1,  1,  1, -1, -1, -1, -1,  1,  1, -1,  1, -1,  1,
        1, -1, -1,  1, -1, -1,  1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1,
        1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1,  1,  1,  1,
        1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1,  1,  1,  1,  1,  1, -1,
        1, -1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1,
        1, -1,  1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1,  1,  1, -1,  1,
        1,  1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  1,  1, -1,  1, -1,  1,
       -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1])

In [11]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

from sklearn.metrics import confusion_matrix


acc = accuracy_score(y_test, y_pred_interpreted)
pre = precision_score(y_test, y_pred_interpreted)
rec = recall_score(y_test, y_pred_interpreted)
f1  = f1_score(y_test, y_pred_interpreted)
auc = roc_auc_score(y_test, y_pred_interpreted)

print(f'accuracy: {acc}')
print(f'precision: {pre}')
print(f'recall: {rec}')
print(f'f1: {f1}')
print(f'auc: {auc}')

accuracy: 0.664179104477612
precision: 0.4939759036144578
recall: 0.9318181818181818
f1: 0.6456692913385826
auc: 0.7325757575757575
