In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys

project_dir_path = '/Users/keisukeonoue/ws/lukasiewicz_1'
sys.path.append(project_dir_path)

import cvxpy as cp
import numpy as np
import pandas as pd 

from src.setup_problem_dual_single_task import Setup

from src.objective_function_single_task import ObjectiveFunction
from src.predicate import Predicate_dual

In [3]:
data_dir_path = os.path.join(project_dir_path, 'inputs/pima_indian_diabetes_3/')
train_data_dir_path = os.path.join(data_dir_path, "train")
file_list = os.listdir(train_data_dir_path)

L_files = [filename for filename in file_list 
           if filename.startswith('L') and filename.endswith('.csv')]

U_files = [filename for filename in file_list 
           if filename.startswith('U') and filename.endswith('.csv')]

file_names_dict = {
    'supervised': L_files,
    'unsupervised': U_files,
    'rule': ['rules_3.txt']
}

train_data_dir_path = os.path.join(data_dir_path, "train")

In [4]:
train_data_file_path = os.path.join(data_dir_path, "test/L_Outcome.csv")
train_data_file_path

'/Users/keisukeonoue/ws/lukasiewicz_1/inputs/pima_indian_diabetes_3/test/L_Outcome.csv'

In [13]:
problem_instance = Setup(
    train_data_dir_path, 
    file_names_dict, 
    ObjectiveFunction, 
    'Outcome', 
    c1=100, 
    c2=10
)

objective, constraints = problem_instance.main()
problem = cp.Problem(objective, constraints)
result = problem.solve(verbose=True)

load_data took 0.04875302314758301 seconds!
load_rules took 0.011752843856811523 seconds!
formulate_predicates_with_cvxpy took 8.606910705566406e-05 seconds!
shape of P: (1807, 1807)
finish l
finish h
finish s
finish l h
finish l s
finish h s
_construct_P_j took 1.0839200019836426 seconds!
construct_constraints took 0.0933678150177002 seconds!
                                     CVXPY                                     
                                     v1.3.2                                    
(CVXPY) Feb 02 03:36:53 PM: Your problem has 36756 variables, 1257 constraints, and 0 parameters.


/Users/keisukeonoue/ws/lukasiewicz_1/myenv/lib/python3.11/site-packages/cvxpy/problems/problem.py:157: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
/Users/keisukeonoue/ws/lukasiewicz_1/myenv/lib/python3.11/site-packages/cvxpy/problems/problem.py:163: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "


(CVXPY) Feb 02 03:36:53 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Feb 02 03:36:53 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Feb 02 03:36:53 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Feb 02 03:36:54 PM: Compiling problem (target solver=OSQP).
(CVXPY) Feb 02 03:36:54 PM: Reduction chain: FlipObjective -> CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> OSQP
(CVXPY) Feb 02 03:36:54 PM: Applying reduction FlipObjective
(CVXPY) Feb 02 03:36:54 PM: Applying reduction CvxAttr2Constr
(CVXPY) Feb 02 03:36:54 PM: Applying reduction Qp2SymbolicQp


/Users/keisukeonoue/ws/lukasiewicz_1/myenv/lib/python3.11/site-packages/cvxpy/problems/problem.py:163: UserWarning: Constraint #4 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "


(CVXPY) Feb 02 03:36:54 PM: Applying reduction QpMatrixStuffing


/Users/keisukeonoue/ws/lukasiewicz_1/myenv/lib/python3.11/site-packages/cvxpy/problems/problem.py:163: UserWarning: Constraint #5 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "


(CVXPY) Feb 02 03:36:59 PM: Applying reduction OSQP
(CVXPY) Feb 02 03:36:59 PM: Finished problem compilation (took 5.607e+00 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Feb 02 03:36:59 PM: Invoking solver OSQP  to obtain a solution.
-----------------------------------------------------------------
           OSQP v0.6.3  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2021
-----------------------------------------------------------------
problem:  variables n = 38563, constraints m = 39820
          nnz(P) + nnz(A) = 1092163
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.0

In [25]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

p_trained = Predicate_dual(
    problem_instance, 
    'Outcome', 
    # metrics=accuracy_score,
    metrics=f1_score,
    opt_iter_num=100
)

[I 2024-02-02 15:46:39,358] A new study created in memory with name: no-name-cab4b51c-4348-4654-a2c7-7409a6e33454
[I 2024-02-02 15:46:39,385] Trial 0 finished with value: 0.0 and parameters: {'b': -1.0946680211453388}. Best is trial 0 with value: 0.0.
[I 2024-02-02 15:46:39,412] Trial 1 finished with value: 0.0 and parameters: {'b': -1.7250973335515725}. Best is trial 0 with value: 0.0.
[I 2024-02-02 15:46:39,455] Trial 2 finished with value: 0.0 and parameters: {'b': -2.230002336328895}. Best is trial 0 with value: 0.0.
[I 2024-02-02 15:46:39,476] Trial 3 finished with value: 0.0 and parameters: {'b': -0.06889696827928349}. Best is trial 0 with value: 0.0.
[I 2024-02-02 15:46:39,490] Trial 4 finished with value: 0.0 and parameters: {'b': -2.6977942840652243}. Best is trial 0 with value: 0.0.
[I 2024-02-02 15:46:39,498] Trial 5 finished with value: 0.0 and parameters: {'b': -0.8294837657597411}. Best is trial 0 with value: 0.0.
[I 2024-02-02 15:46:39,510] Trial 6 finished with value: 0


min_bound: -3.0379200005446068
max_bound: 1.9620799994553935



[I 2024-02-02 15:46:39,592] Trial 10 finished with value: 0.49014084507042255 and parameters: {'b': 1.6272167093190966}. Best is trial 6 with value: 0.49014084507042255.
[I 2024-02-02 15:46:39,604] Trial 11 finished with value: 0.49014084507042255 and parameters: {'b': 0.5462199586485881}. Best is trial 6 with value: 0.49014084507042255.
[I 2024-02-02 15:46:39,625] Trial 12 finished with value: 0.49014084507042255 and parameters: {'b': 0.6265392949944593}. Best is trial 6 with value: 0.49014084507042255.
[I 2024-02-02 15:46:39,649] Trial 13 finished with value: 0.5865724381625442 and parameters: {'b': 0.3558341810017346}. Best is trial 13 with value: 0.5865724381625442.
[I 2024-02-02 15:46:39,677] Trial 14 finished with value: 0.0 and parameters: {'b': -0.0695082274137222}. Best is trial 13 with value: 0.5865724381625442.
[I 2024-02-02 15:46:39,692] Trial 15 finished with value: 0.49014084507042255 and parameters: {'b': 1.096206329953004}. Best is trial 13 with value: 0.586572438162544

In [26]:
p_trained.coeff

array([0.00996556, 0.08746423, 0.0659938 , 0.05620022, 0.06266074,
       0.06755724, 0.16267144, 0.32771598])

In [27]:
data = pd.read_csv(train_data_file_path, index_col=0)
X_test, y_test = data.drop(['target'], axis=1), data['target']

In [28]:
y_pred = p_trained(X_test)
y_pred

array([0.48070851, 0.6715182 , 0.50735089, 0.45677911, 0.49337707,
       0.55552087, 0.53171118, 0.46099335, 0.48638755, 0.48464721,
       0.44468492, 0.53990346, 0.56277292, 0.4547266 , 0.51763692,
       0.5017967 , 0.57805155, 0.57529001, 0.48466629, 0.41953856,
       0.53240075, 0.44530788, 0.43457832, 0.52949786, 0.4582967 ,
       0.48398345, 0.50839837, 0.57301186, 0.427913  , 0.57899014,
       0.58076958, 0.50417685, 0.62918034, 0.56760721, 0.57027273,
       0.48555043, 0.4436554 , 0.53359646, 0.60595097, 0.6145672 ,
       0.5810127 , 0.67686286, 0.59406073, 0.4625945 , 0.50440895,
       0.67654307, 0.55863035, 0.5566977 , 0.63269707, 0.5961108 ,
       0.50667637, 0.53193159, 0.49873511, 0.60551347, 0.5577608 ,
       0.53510616, 0.52573648, 0.50480402, 0.5482163 , 0.55975392,
       0.48401714, 0.44989845, 0.52389485, 0.56927605, 0.57053175,
       0.63603142, 0.55850739, 0.4969563 , 0.59094093, 0.46938864,
       0.5273392 , 0.51613822, 0.46326148, 0.5738665 , 0.60707

In [29]:
y_pred_interpreted = np.where(y_pred >= 0.5, 1, -1)
y_pred_interpreted

array([-1,  1,  1, -1, -1,  1,  1, -1, -1, -1, -1,  1,  1, -1,  1,  1,  1,
        1, -1, -1,  1, -1, -1,  1, -1, -1,  1,  1, -1,  1,  1,  1,  1,  1,
        1, -1, -1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1,  1,  1, -1,
        1, -1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1,
        1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1,
        1,  1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  1,  1, -1,  1, -1,  1,
       -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1])

In [30]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

from sklearn.metrics import confusion_matrix


acc = accuracy_score(y_test, y_pred_interpreted)
pre = precision_score(y_test, y_pred_interpreted)
rec = recall_score(y_test, y_pred_interpreted)
f1  = f1_score(y_test, y_pred_interpreted)
auc = roc_auc_score(y_test, y_pred_interpreted)

print(f'accuracy: {acc}')
print(f'precision: {pre}')
print(f'recall: {rec}')
print(f'f1: {f1}')
print(f'auc: {auc}')

accuracy: 0.6194029850746269
precision: 0.4606741573033708
recall: 0.9318181818181818
f1: 0.6165413533834587
auc: 0.6992424242424242
