In [ ]:
%load_ext autoreload
%autoreload 2

In [29]:
import time

import numpy as np

def compute_kernel_matrix(X1, X2, kernel_function=np.dot):
    """
    Compute the kernel matrix between two matrices.

    Parameters:
    - X1: First input matrix (n x m)
    - X2: Second input matrix (n x m)
    - kernel_function: Kernel function to use (default is dot product)

    Returns:
    - Kernel matrix (n x n)
    """
    n1, m1 = X1.shape
    n2, m2 = X2.shape

    if m1 != m2:
        raise ValueError("Input matrices must have the same number of features (columns)")

    K_matrix = np.zeros((n1, n2))

    for i in range(n1):
        for j in range(n2):
            K_matrix[i, j] = kernel_function(X1[i, :], X2[j, :])

    return K_matrix

In [26]:
var = 1000
data = np.random.randint(low=0, high=5, size=(var, 30))

X = data[:, :-1]
y = data[:, -1]

P = np.zeros(shape=(var, var))
P

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [27]:
s = time.time()


for i in range(var):
    for i_ in range(var):
        P[i, i_] = y[i] * y[i_] * np.dot(X[i], X[i_])


e = time.time()
print(e - s)

P

0.890099048614502


array([[   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0., 1656., ...,  666.,  732.,  834.],
       ...,
       [   0.,    0.,  666., ...,  712.,  384.,  512.],
       [   0.,    0.,  732., ...,  384.,  768.,  472.],
       [   0.,    0.,  834., ...,  512.,  472.,  680.]])

In [41]:
s = time.time()

K = compute_kernel_matrix(X, X)
for i in range(var):
    for i_ in range(var):
        P[i, i_] = y[i] * y[i_] * K[i, i_]

e = time.time()
print(e - s)

P

1.1233890056610107


array([[   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0, 1656, ...,  666,  732,  834],
       ...,
       [   0,    0,  666, ...,  712,  384,  512],
       [   0,    0,  732, ...,  384,  768,  472],
       [   0,    0,  834, ...,  512,  472,  680]])

In [40]:
import time
import numpy as np

s = time.time()

K = compute_kernel_matrix(X, X)

P = np.einsum('i, j, ik, ik -> ij', y, y, X, X, optimize=True)

e = time.time()
print(e - s)
print(P)


0.725111722946167
[[   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0 1656 ... 1104 1104 1104]
 ...
 [   0    0 1068 ...  712  712  712]
 [   0    0 1152 ...  768  768  768]
 [   0    0 1020 ...  680  680  680]]
